### ISSUE TITLE
Snapchat API

### ISSUE THREAD

**Issue by h4ck1th4rd** [vladhq/snapchat-client-php#1]
looking for snapchat private API.

skype me at: mzaboss

**Comment by vladbondarenko97** [comment]
You won't be able to access their API if it's private. They used to have an unofficial API that they made public, but they closed that down and that's why none of the Snapchat clients work anymore.

**Comment by h4ck1th4rd** [comment]
That's Incorrect, the Unofficial API still works, Casper and specter, and many services are using it.
